apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.16.70.57:8001
  name: ilon1
- cluster:
    certificate-authority: /Users/smith/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.30.223.14:8001
  name: mycluster
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.30.214.196:8001
  name: mycluster.icp
contexts:
- context:
    cluster: ilon1
    namespace: kube-system
    user: user7
  name: ilon1-context
- context:
    cluster: minikube
    user: minikube
  name: minikube
- context:
    cluster: mycluster
    namespace: cert-manager
    user: admin
  name: mycluster-context
- context:
    cluster: mycluster.icp
    namespace: default
    user: admin
  name: mycluster.icp-context
current-context: ilon1-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiNWUyNzllNGI4ZGYxYTFmNmQzZDZjOTY2NjMyYWRiNWQ4ZWRjOGMwZiIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiMTQ0MWMxMjJkNTllMTZmYjc3OTUyNmM5N2RkMDhmZjMiLCJleHAiOjE1NTc5MjYyNTQsImlhdCI6MTU1Nzg5NzQ1NCwic3ViIjoiYWRtaW4iLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbXX0.vln8wH5tpPrcmMH0AoPpGZ4-1HLDWUKMy0Cym3EcUjRk7rRhdXvkX9WK6bvusry785Oe8kifaMy5_OfOaty3B7aesLqHsjLIZCfmAIhEJuwfVI7CxvbYH9RvY9UMGGJVamqy6jNSub0GqsFFtf4fFoqFVN9UALX9WysqYgW9g6BnBaYiper8bsgFALYZwBq9FSE5IHIV9AIBTf0kkfu3T0l1fN2C0aop7J3kc7s81OHQt0khkju7y0PdRyiDTjRfb6BukVPEmKB4EaCiuzGJRrjdGdanj55Ezq59A7S9cFqqVV_w9418SFbjmgYVyXzfDt0nQzwK368dxXnIFL3o5Q
- name: minikube
  user:
    client-certificate: /Users/smith/.minikube/client.crt
    client-key: /Users/smith/.minikube/client.key
- name: user7
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiZWUxZWE4YTE1ZDRlMzM1NzUzOGRkNTU2YmQ3Mjg0ZGEwNGUxOTZlZCIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjciLCJpc3MiOiJodHRwczovL2lsb24xLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiJkMGIwOGIzZGQxYWUzM2FlNWRhNTE1YzQwZGRhYWZlYyIsImV4cCI6MTU1ODY1OTI5NywiaWF0IjoxNTU4NjMwNDk3LCJzdWIiOiJ1c2VyNyIsInRlYW1Sb2xlTWFwcGluZ3MiOlsiaWNwOnRlYW0tMDc6YWRtaW4iLCJpY3A6ZGVmYXVsdDptZW1iZXIiLCJpY3A6ZGVmYXVsdDp0ZWFtYWRtaW4iXX0.RJG6viOt8ivDjkkaf52uBdhT2jysr2WiILLaW1UBn5D33YygkQp0o4Jr9Hc_MQ-hhH4WoM0NvLtxr0bybAMEWahR2YlY4p1fla9sLL9-NBufkPUrSAuAzwFbwknMG3DrMCNNZ6obQ0usX6T1sjxvJ9X6aPDtENoPdalqKxl6cqcj8xPEbH_zgjYJxo_DNBUMiPN06p7ic8wbB8ZV6V16JBkOFFz_PZ6Kauei5YCPFPEbzo4DTvzF5Qsaj90C5XFZ-pbHudRYTeb5cwR6j56mFOJ3kEIg4DOZl4ywxPrRuD9PuW9Nf03AghGGkZLC0YzSKhmBVbdg-RcMSe5wmbSiGQ
