apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: sumapp
  labels:
    app: sumapp
spec:
  selector:
    matchLabels:
      app: sumapp
  replicas: 1
  template:
    metadata:
      labels:
        app: sumapp
    spec:
      containers:
      - name: sumapp
        image: mycluster.icp:8500/default/$APPNAME
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
apiVersion: v1        
kind: Service
metadata:
  name: sumapp
  labels:
    app: sumapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9080
  selector:
   app: sumapp
